version: '2'

services:
    abp_migrator:
        build: abp/migrator
        volumes:
            - "./App_Data:/app/App_Data"
    abp_host:
        build: abp/host
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9901:80"
        volumes:
            - "./App_Data:/app/App_Data"

    abp_ng:
        build: abp/ng
        ports:
            - "9902:80"
        depends_on:
            - abp_host